"""Step 3 of the plan: frequency tallies over the parsed FRA scripts.

No vocabulary is assumed here. Every tally is a raw count of a string
that appears in the scripts. Each row shows (occurrences, distinct cards)
so a primitive used 40 times by one card is not mistaken for a theme.

Forge's DeckHas/DeckHints SVars are hand-authored synergy labels. They
are tallied separately and are NOT an input to anything downstream;
they are held out as an independent check on the emergent graph.
"""
import json, re, sys, collections

cards = json.load(open(sys.argv[1], encoding="utf-8"))
OUT_MD, OUT_JSON = sys.argv[2], sys.argv[3]

T = collections.defaultdict(lambda: collections.defaultdict(lambda: [0, set()]))


def bump(table, key, card):
    e = T[table][key]; e[0] += 1; e[1].add(card)


COST_TOKEN = re.compile(r"([A-Za-z]+)<([^>]*)>|\b(T|Q|X)\b")
VALID_KEYS = re.compile(r"^(Valid\w*|Affected|Defined|TgtPrompt)$")

for c in cards:
    nm = c["name"]
    for f in c["faces"]:
        for kw in f["keywords"]:
            bump("keyword", kw.split(":")[0].strip(), nm)
        for t in (f["types"] or "").split():
            bump("type_word", t, nm)
        for ab in f["abilities"]:
            k, head, api, p = ab["kind"], ab["head"], ab["api"], ab["params"]
            if head in ("AB", "SP", "DB"):
                bump("effect_api", api, nm)
                bump("effect_api_by_head", f"{head}${api}", nm)
            elif k == "T" or (k == "SVar" and head == "Mode"):
                bump("trigger_mode", api, nm)
                # the zone-change shape is the main discriminator for ChangesZone
                if api in ("ChangesZone", "ChangesZoneAll"):
                    bump("trigger_changeszone_shape",
                         f"{p.get('Origin','Any')}->{p.get('Destination','Any')}", nm)
                if api in ("CounterAdded", "CounterAddedOnce", "CounterRemoved",
                           "CounterRemovedOnce", "CounterPlayerAddedAll", "CounterAddedAll"):
                    bump("trigger_counter_type", f"{api}:{p.get('CounterType','Any')}", nm)
            elif k == "S":
                bump("static_mode", api, nm)
            elif k == "R":
                bump("replacement_event", api, nm)
            for key, val in p.items():
                if key == "CounterType":
                    for ct in val.split(","):
                        bump("counter_type", ct.strip(), nm)
                if VALID_KEYS.match(key):
                    bump("valid_expr", f"{key}$ {val}", nm)
                    # the leading type word of each filter, e.g. Creature.YouCtrl -> Creature
                    for alt in val.split(","):
                        bump("valid_head", alt.strip().split(".")[0].split("+")[0], nm)
                if key in ("Origin", "Destination") and head in ("AB", "SP", "DB"):
                    bump("effect_zone", f"{api}:{key}={val}", nm)
                if key == "Cost":
                    for m in COST_TOKEN.finditer(val):
                        tok = m.group(1) or m.group(3)
                        bump("cost_verb", tok, nm)
                        if m.group(1) in ("SubCounter", "AddCounter"):
                            bump("cost_counter", f"{m.group(1)}:{m.group(2).split('/')[1] if '/' in m.group(2) else m.group(2)}", nm)
                for cm in re.finditer(r"(?<![A-Za-z])Count\$([A-Za-z]+)", val):
                    bump("count_expr", cm.group(1), nm)
                if key in ("Produced",) and api == "Mana":
                    bump("mana_produced", val, nm)
        for sv, raw in f["svars"].items():
            for cm in re.finditer(r"(?<![A-Za-z])Count\$([A-Za-z]+)", raw):
                bump("count_expr", cm.group(1), nm)
        # DeckHas/DeckHints/DeckNeeds are top-level lines, e.g.
        # "DeckHas:Ability$Graveyard & Type$Zombie"
        for key in ("DeckHas", "DeckHints", "DeckNeeds"):
            for raw in f["other"].get(key, []):
                for part in re.split(r"\s*&\s*|\s*\|\s*", raw):
                    if not part: continue
                    kind, _, vals = part.partition("$")
                    for v in vals.split(","):
                        bump(f"HELDOUT_{key}", f"{kind}${v.strip()}", nm)

ORDER = ["effect_api", "trigger_mode", "trigger_changeszone_shape", "trigger_counter_type",
         "static_mode", "replacement_event", "counter_type", "cost_verb", "cost_counter",
         "count_expr", "effect_zone", "mana_produced", "valid_head", "valid_expr", "keyword",
         "type_word", "HELDOUT_DeckHas", "HELDOUT_DeckHints", "HELDOUT_DeckNeeds"]

js = {t: sorted(([k, v[0], len(v[1]), sorted(v[1])] for k, v in T[t].items()),
               key=lambda r: (-r[2], -r[1], r[0])) for t in ORDER if t in T}
json.dump(js, open(OUT_JSON, "w"), indent=1, ensure_ascii=False)

with open(OUT_MD, "w", encoding="utf-8") as fh:
    fh.write("# FRA script tallies (generated by `tally.py`, do not edit)\n\n")
    fh.write(f"Cards: {len(cards)}. Each row: `key` — occurrences / distinct cards. "
             "Rows used by exactly one card list it.\n\n")
    for t in js:
        rows = js[t]
        fh.write(f"## {t} ({len(rows)} distinct)\n\n")
        limit = 60 if t != "valid_expr" else 80
        for k, n, d, who in rows[:limit]:
            tail = f" — {who[0]}" if d == 1 else ""
            fh.write(f"- `{k}` — {n} / {d}{tail}\n")
        if len(rows) > limit:
            fh.write(f"- … {len(rows) - limit} more in `tallies.json`\n")
        fh.write("\n")

for t in ORDER:
    if t in js:
        print(t, len(js[t]), " ".join(f"{k}:{d}" for k, n, d, _ in js[t][:12]))
