#!/usr/bin/env python3
"""Generate rl/phase13.py (the 13c controller) from rl/phase12.py, which stays untouched.
    python3 rl/make_phase13.py
Changes (rl/PHASE13-BC.md 13c): one main M_B on BenchDimir from the clone (P13_START, default
rl/artifacts/v7/13/bc/bc.pt), state in /tmp/rl_13_M_B, artifacts rl/artifacts/v7/13/c; the Phase 12
recipe, rotation and per-block 25-game CP7 check unchanged; levels every 1,024 episodes in THREE
readouts (sampled = battery_p12s.sh; two-stage = battery_xdeck.sh + --argmax-two-stage; argmax-classes =
battery_xdeck.sh), graduation on sampled OR two-stage (>= 0.70, Wilson lower >= 0.60, n >= 100); no
unseen suite; the start level and census are the 13b rows unless --start-level / --start-census; an
opt=None start checkpoint is stripped of its opt key when restored to agent.pt; tags L13.
"""
import re

SRC = "/home/user/CardGuru/rl/phase12.py"
DST = "/home/user/CardGuru/rl/phase13.py"
s = open(SRC).read()


def sub1(old, new):
    global s
    assert s.count(old) == 1, (s.count(old), old[:60])
    s = s.replace(old, new)


def span(h1, h2, new):
    """replace from header h1 up to (not including) header h2"""
    global s
    i = s.index(h1)
    j = s.index(h2, i)
    s = s[:i] + new + s[j:]


s = s.replace("#!/usr/bin/env python3\n", "#!/usr/bin/env python3\n# GENERATED by rl/make_phase13.py from rl/phase12.py "
              "(Phase 13c controller; edit the generator, not this file).\n", 1)
sub1('ART = f"{LB}/rl/artifacts/v7/12"', 'ART = f"{LB}/rl/artifacts/v7/13/c"\n'
     'START = os.environ.get("P13_START", f"{LB}/rl/artifacts/v7/13/bc/bc.pt")\n'
     'READOUTS = ["sampled", "twostage", "argmax"]\n'
     'TWO = "--device cuda --logit-bound 5 --argmax-classes --argmax-two-stage"')
i = s.index("MAINS = {")
j = s.index('ORDER = ["M_D", "M_L", "M_W"]')
s = s[:i] + 'MAINS = {  # name: (deck, starting snapshot, lane seed)\n    "M_B": ("BenchDimir", START, 31),\n}\n' \
    + 'ORDER = ["M_B"]' + s[j + len('ORDER = ["M_D", "M_L", "M_W"]'):]
sub1("CENSUS_SEED = 12500", "CENSUS_SEED = 13700")
sub1('"unseen_k", "unseen_n", "graduated", "ckpt"]', '"unseen_k", "unseen_n", "graduated", "ckpt", "two_k", "two_n", "arg_k", "arg_n"]')
s = s.replace('"L12"', '"L13"')
sub1('.replace("L11|", "L12|", 1)', '.replace("L11|", "L13|", 1)')
sub1('f"/tmp/rl_12_{m}"', 'f"/tmp/rl_13_{m}"')
s = s.replace('f"p12_{m}_', 'f"p13_{m}_')

# battery(): a readout argument
span("def battery(ck, deck, rows, games, out):", "def white_fields(", '''def battery(ck, deck, rows, games, out, ro="argmax"):
    """one row set in one readout; returns {(kind, deck): (k, n, stalls)}, the pooled (k, n), the raw XDECK lines.
    sampled = rl/battery_p12s.sh (frozen, -Drl.mode=train); twostage / argmax = rl/battery_xdeck.sh."""
    free_lane()
    env = dict(os.environ, G=str(games), ROWS=rows)
    script = "battery_p12s.sh" if ro == "sampled" else "battery_xdeck.sh"
    if ro == "twostage":
        env["SRVEXTRA"] = TWO
    p = subprocess.run(["bash", f"{RL}/{script}", ck, deck, out], env=env, capture_output=True,
                       text=True, cwd="/home/user/CardGuru")
    res, lines = {}, [ln for ln in p.stdout.splitlines() if ln.startswith("XDECK|")]
    for ln in lines:
        m = XD.search(ln)
        if m:
            st = re.search(r"stalls=(\\d+)", ln)
            res[(m.group(1), m.group(2))] = (int(m.group(3)), int(m.group(4)), int(st.group(1)) if st else 0)
    k = sum(v[0] for v in res.values())
    n = sum(v[1] for v in res.values())
    with open(f"{ART}/battery_lines.txt", "a") as fh:
        fh.write("\\n".join(f"{ro}|{ln}" for ln in lines) + "\\n")
    return res, (k, n), lines


''')

span("    def level(self, m, ck, point):", "    def unseen(self, ck, deck, out):", '''    def level(self, m, ck, point):
        L = self.st["mains"][m]
        deck, ta = L["deck"], ck_episodes(ck)
        base = f"{ART}/levels/{m}_{point}_{ta:05d}"
        lev = {"point": point, "trained": ta, "ck": ck}
        grad = 0
        for ro in READOUTS:
            rc, _, _ = battery(ck, deck, f"cp7:{deck}", self.a.level_games, f"{base}_{ro}_cp7", ro)
            rh, _, _ = battery(ck, deck, f"heuristic:{deck}", self.a.guard_games, f"{base}_{ro}_heur", ro)
            ck7, n7, s7 = rc.get(("cp7", deck), (0, 0, 0))
            kh, nh, _ = rh.get(("heuristic", deck), (0, 0, 0))
            lo, hi = wilson(ck7, n7) if n7 else (0.0, 0.0)
            g = int(n7 >= 100 and ck7 / n7 >= 0.70 and lo >= 0.60)
            lev[ro] = {"cp7": [ck7, n7], "heur": [kh, nh], "stalls": s7, "grad": g}
            if ro in ("sampled", "twostage"):       # argmax-classes is not a graduation readout (13c)
                grad = grad or g
        for key in ("cp7", "heur", "stalls"):
            lev[key] = lev["sampled"][key]
        lev["graduated"] = grad
        return lev, base

''')

span("    def level_line(self, m, lev, extra=\"\"):", "    # ------------------------------------------------------------ tasks", '''    def level_line(self, m, lev, extra=""):
        L = self.st["mains"][m]
        k, n = lev["cp7"]
        kh, nh = lev["heur"]
        lo, hi = wilson(k, n) if n else (0, 0)
        loh, hih = wilson(kh, nh) if nh else (0, 0)
        two = lev.get("twostage", {}).get("cp7", ["", ""])
        arg = lev.get("argmax", {}).get("cp7", ["", ""])
        self.tsv("levels.tsv", [utc(), f"{self.hour():.3f}", m, lev["point"], lev["trained"], k, n,
                                f"{k / n:.3f}" if n else "", f"{lo:.3f}", f"{hi:.3f}", kh, nh,
                                f"{kh / nh:.3f}" if nh else "", f"{loh:.3f}", f"{hih:.3f}",
                                "", "", lev["graduated"], os.path.basename(lev["ck"]), two[0], two[1], arg[0], arg[1]])
        parts = ["L13", "level", m, f"point={lev['point']}", f"h={self.hour():.2f}", f"trained={lev['trained']}",
                 f"gained={lev['trained'] - L['start_ep']}"]
        for ro in READOUTS:
            r = lev.get(ro)
            if r:
                parts += [f"{ro}_cp7={fmt(*r['cp7'])}", f"{ro}_heur={fmt(*r['heur'])}", f"{ro}_stalls={r['stalls']}"]
        parts.append(f"graduated={lev['graduated']}" + extra)
        say(*parts)

''')

span("    def t_start(self, m):", "    def t_check(self, m, ck, ta, n):", '''    def t_start(self, m):
        L = self.st["mains"][m]
        ck = L["start_ck"]
        if self.a.start_level:
            lev, _ = self.level(m, ck, "start")
            L["levels"].append(lev)
            self.save()
            self.level_line(m, lev)
        say("L13", "start", m, f"ck={os.path.basename(ck)}", f"episodes={L['start_ep']}",
            f"start_level={'measured' if self.a.start_level else 'the 13b row'}",
            f"start_census={'recorded' if self.a.start_census else 'the 13b row'}")
        if self.a.start_census:
            self.census(m, ck, f"p13_{m}_start")

''')

span("    def t_level(self, m, ck):", "    def t_end(self, m):", '''    def t_level(self, m, ck):
        L = self.st["mains"][m]
        lev, _ = self.level(m, ck, "train")
        L["levels"].append(lev)
        self.save()
        self.level_line(m, lev)
        if lev["graduated"] and not L["graduated"]:
            L["graduated"] = True
            g = f"{ART}/pool/{m}_grad.pt"
            shutil.copyfile(ck, g)
            self.save()
            say("L13", "grad", m, f"h={self.hour():.2f}", f"trained={lev['trained']}",
                f"gained={lev['trained'] - L['start_ep']}", f"sampled={fmt(*lev['sampled']['cp7'])}",
                f"twostage={fmt(*lev['twostage']['cp7'])}", f"frozen={g}")

''')

span("    def t_end(self, m):", "    def ensure_agent(self, m):", '''    def t_end(self, m):
        L = self.st["mains"][m]
        if L["trained"] == L["start_ep"]:
            say("L13", "end", m, "no training - nothing to level")
            return
        if L["levels"] and L["levels"][-1]["trained"] == L["trained"]:
            say("L13", "end", m, f"last level already at {L['trained']}")
            return
        lev, _ = self.level(m, L["latest"], "end")
        L["levels"].append(lev)
        self.save()
        self.level_line(m, lev)

''')

sub1('''            shutil.copyfile(L["latest"], agent)
''', '''            shutil.copyfile(L["latest"], agent)
            c = torch.load(agent, map_location="cpu", weights_only=False)
            if "opt" in c and c["opt"] is None:      # a BC checkpoint (opt=None) resumes like a stripped snapshot
                c.pop("opt")
                torch.save(c, agent + ".tmp")
                os.replace(agent + ".tmp", agent)
''')

sub1('ap.add_argument("--hours", type=float, default=10.5,', 'ap.add_argument("--hours", type=float, default=12.0,')
sub1('    ap.add_argument("--dry-run", action="store_true")',
     '    ap.add_argument("--start-level", action="store_true", help="measure the start level (default: the 13b row)")\n'
     '    ap.add_argument("--start-census", action="store_true", help="record the start census (default: the 13b row)")\n'
     '    ap.add_argument("--dry-run", action="store_true")')
s = s.replace('"rotation=" + ",".join(ROTATION))', '"rotation=" + ",".join(ROTATION), "readouts=" + ",".join(READOUTS))')
open(DST, "w").write(s)
print(f"MAKE13|ok|{DST}|lines={s.count(chr(10))}")
