#!/usr/bin/env python3
# GENERATED by rl/make_phase13.py from rl/phase12.py (Phase 13c controller; edit the generator, not this file).
"""Phase 12 controller (rl/PHASE12-CP7.md): warm start each deck main to competence vs CP7.

One lane at a time, blocks rotate M_D (BenchDimir), M_L (G1Landfall), M_W (W0Base); a
graduated main stops training.  Per trainee block: one 256-episode block of
rl/rung0_lane_league.sh resumed from the main's own OUT dir (/tmp/rl_12_<main>/agent.pt),
opponent from the pre-stated 75 % CP7 / 25 % heuristic mix on the own mirror, realised
EXACTLY per 1,024-episode window by the fixed rotation cp7, heuristic, cp7, cp7 (Phase 10's
Amendment 3 lesson: random draws under-delivered a 10-15 % bucket), then the 25-game CP7
census check (rl/record_census.sh, fixed seed 12500 so every check sees the same deals).
At every 1,024 episodes of a main: the 100-game CP7 level + the 50-game heuristic guard
(rl/battery_xdeck.sh; its row seeds are fixed, so every level sees the same deals).
Graduated = CP7 level >= 0.70 AND Wilson lower bound >= 0.60; the unseen 3-deck suite
(heuristic on BenchBurn / HoldoutControl / HoldoutMidrange, 50 each) at the start, at
graduation, and at the end for a main that did not graduate.
Before training ("start" task per main): CP7 100 + heuristic 50 + unseen 150 + the census.

Lines: L12|start|..  L12|block|..  L12|tput|..  L12|check|..  L12|level|..  L12|grad|..
       L12|end|..  L12|done|reason=..
Resumable: state in rl/artifacts/v7/12/state.json (pending block, todo list, clock).
Stop: touch rl/artifacts/v7/12/STOP (finishes the current step; no end phase).
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time

sys.path.insert(0, "/home/user/CardGuru/rl")
import torch  # noqa: E402
from league11 import wilson, check_line, ck_episodes, RL, LB, SRVEXTRA  # noqa: E402

ART = f"{LB}/rl/artifacts/v7/13/c"
START = os.environ.get("P13_START", f"{LB}/rl/artifacts/v7/13/bc/bc.pt")
READOUTS = ["sampled", "twostage", "argmax"]
TWO = "--device cuda --logit-bound 5 --argmax-classes --argmax-two-stage"
MAINS = {  # name: (deck, starting snapshot, lane seed)
    "M_B": ("BenchDimir", START, 31),
}
ORDER = ["M_B"]
ROTATION = ["cp7", "heuristic", "cp7", "cp7"]      # exact 75/25 per 1,024-episode window
UNSEEN = "heuristic:BenchBurn heuristic:HoldoutControl heuristic:HoldoutMidrange"
W_UNSEEN_P10 = f"{LB}/rl/artifacts/v7/10/eval/M_W_s1end_unseen"   # same ckpt, same suite (Phase 10)
LANE_PORT, OPP_PORT, LANE_DPORT = 7950, 7960, 7912
CENSUS_SEED = 13700
RES_COLS = ["n", "time_utc", "hour", "main", "trained_before", "trained_after", "opp_kind", "episodes",
            "wins", "losses", "draws", "stalls", "win_rate", "job_errors", "snapshot", "wall_s", "rc"]
LEV_COLS = ["time_utc", "hour", "main", "point", "trained", "cp7_k", "cp7_n", "cp7_p", "cp7_lo", "cp7_hi",
            "heur_k", "heur_n", "heur_p", "heur_lo", "heur_hi", "unseen_k", "unseen_n", "graduated", "ckpt", "two_k", "two_n", "arg_k", "arg_n"]


def utc():
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def say(*parts):
    print("|".join(str(p) for p in parts), flush=True)


def fmt(k, n):
    if not n:
        return "NA"
    lo, hi = wilson(k, n)
    return f"{k}/{n} = {k / n:.3f} [{lo:.3f},{hi:.3f}]"


def quiet(cmd):
    subprocess.call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def free_lane():
    """Nothing of the lane stays resident beside a battery or a census (<= 2 servers + 2 JVMs)."""
    quiet(["pkill", "-f", f"policy_serve[r].py --port {LANE_PORT}"])
    quiet(["pkill", "-f", f"policy_serve[r].py --port {OPP_PORT}"])
    quiet(["bash", f"{RL}/driver_server.sh", "stop", str(LANE_DPORT)])


XD = re.compile(r"vs=(\w+)\|oppDeck=(\w+)\|(\d+)/(\d+) = ")


def battery(ck, deck, rows, games, out, ro="argmax"):
    """one row set in one readout; returns {(kind, deck): (k, n, stalls)}, the pooled (k, n), the raw XDECK lines.
    sampled = rl/battery_p12s.sh (frozen, -Drl.mode=train); twostage / argmax = rl/battery_xdeck.sh."""
    free_lane()
    env = dict(os.environ, G=str(games), ROWS=rows)
    script = "battery_p12s.sh" if ro == "sampled" else "battery_xdeck.sh"
    if ro == "twostage":
        env["SRVEXTRA"] = TWO
    p = subprocess.run(["bash", f"{RL}/{script}", ck, deck, out], env=env, capture_output=True,
                       text=True, cwd="/home/user/CardGuru")
    res, lines = {}, [ln for ln in p.stdout.splitlines() if ln.startswith(("XDECK|", "XDECKS|"))]  # battery_p12s.sh prints XDECKS|
    for ln in lines:
        m = XD.search(ln)
        if m:
            st = re.search(r"stalls=(\d+)", ln)
            res[(m.group(1), m.group(2))] = (int(m.group(3)), int(m.group(4)), int(st.group(1)) if st else 0)
    k = sum(v[0] for v in res.values())
    n = sum(v[1] for v in res.values())
    with open(f"{ART}/battery_lines.txt", "a") as fh:
        fh.write("\n".join(f"{ro}|{ln}" for ln in lines) + "\n")
    return res, (k, n), lines


def white_fields(text, prefix):
    """M_W check fields: blocks matching the combat search, attack windows, creatures per game."""
    blk = blk_m = atk = atk_decl = atk_m = 0
    try:
        for ln in open(prefix + ".audit.txt", errors="replace"):
            if "[atkaudit] policy " in ln:
                atk += 1
                body = ln.split("[atkaudit] policy ", 1)[1]
                atk_decl += 0 if body.startswith("(none)") else 1
                atk_m += ln.rstrip().endswith("MATCH")
            elif "[audit] policy " in ln:
                blk += 1
                blk_m += ln.rstrip().endswith("MATCH")
    except OSError:
        pass
    cpg = "-"
    if os.path.exists(prefix + ".jsonl"):
        os.makedirs("/tmp/p12wc", exist_ok=True)
        p = subprocess.run([sys.executable, f"{RL}/dimir_census.py", "--out", "/tmp/p12wc", f"w={prefix}.jsonl"],
                           capture_output=True, text=True)
        m = re.search(r"creatures_cast_per_game=([0-9.]+)", p.stdout)
        cpg = m.group(1) if m else "-"
    g = int((re.search(r"\|games=(\d+)", text) or [0, 0])[1])
    return [f"blocks_match={blk_m}/{blk}", f"attack_windows={atk}", f"attacks_declared={atk_decl}/{atk}",
            f"attack_match={atk_m}/{atk}", f"attacks_pg={atk_decl / g:.1f}" if g else "attacks_pg=NA", f"cpg={cpg}"]


class P12:
    def __init__(self, a):
        self.a = a
        os.makedirs(f"{ART}/pool", exist_ok=True)
        self.sp = f"{ART}/state.json"
        if os.path.exists(self.sp):
            self.st = json.load(open(self.sp))
            say("L13", "resume", f"n={self.st['n']}", f"h={self.hour():.2f}", f"todo={len(self.st['todo'])}")
        else:
            self.st = {"t0": time.time(), "n": 0, "rot": 0, "fails": 0, "pending": None,
                       "todo": [["start", m] for m in ORDER], "mains": {}}
            for m in ORDER:
                deck, ck, seed = MAINS[m]
                ep = ck_episodes(ck)
                self.st["mains"][m] = {"deck": deck, "start_ck": ck, "seed": seed, "out": f"/tmp/rl_13_{m}",
                                       "start_ep": ep, "trained": ep, "latest": ck, "blocks": 0,
                                       "graduated": False, "levels": [], "tput": None}
            self.save()
        for f, cols in (("results.tsv", RES_COLS), ("levels.tsv", LEV_COLS)):
            if not os.path.exists(f"{ART}/{f}"):
                open(f"{ART}/{f}", "w").write("\t".join(cols) + "\n")

    def hour(self):
        return (time.time() - self.st["t0"]) / 3600.0

    def save(self):
        json.dump(self.st, open(self.sp + ".tmp", "w"), indent=1)
        os.replace(self.sp + ".tmp", self.sp)

    def tsv(self, f, row):
        with open(f"{ART}/{f}", "a") as fh:
            fh.write("\t".join(str(x) for x in row) + "\n")

    # ------------------------------------------------------------ measurements
    def census(self, m, ck, tag, n=None):
        free_lane()
        L = self.st["mains"][m]
        p = subprocess.run(["bash", f"{RL}/record_census.sh", ck, L["deck"], "cp7", str(self.a.census_games), tag,
                            str(CENSUS_SEED)], capture_output=True, text=True, cwd="/home/user/CardGuru")
        lines = [ln for ln in p.stdout.splitlines() if ln.startswith(("CENSUSREC|", "DC|", "LC|"))]
        with open(f"{ART}/census_lines.txt", "a") as fh:
            fh.write("\n".join(lines) + "\n")
        text = "\n".join(lines)
        n, h, ta = (self.st["n"] if n is None else n), self.hour(), ck_episodes(ck)
        if m == "M_W":
            w = int((re.search(r"wins=(\d+)", text) or [0, 0])[1])
            g = int((re.search(r"\|games=(\d+)", text) or [0, 0])[1])
            c = int((re.search(r"\|consults=(\d+)", text) or [0, 0])[1])
            parts = ["L13", "check", m, f"n={n}", f"h={h:.2f}", f"trained={ta}", "opp=cp7", f"wr={fmt(w, g)}"]
            parts += white_fields(text, f"{LB}/rl/artifacts/v7/11/rec_{tag}")
            parts.append(f"consults_pg={c / g:.1f}" if g else "consults_pg=NA")
            say(*parts)
        else:
            say(check_line(m, n, h, ta, "cp7", text).replace("L11|", "L13|", 1) + f"|tag={tag}")

    def level(self, m, ck, point):
        L = self.st["mains"][m]
        deck, ta = L["deck"], ck_episodes(ck)
        base = f"{ART}/levels/{m}_{point}_{ta:05d}"
        lev = {"point": point, "trained": ta, "ck": ck}
        grad = 0
        for ro in READOUTS:
            rc, _, _ = battery(ck, deck, f"cp7:{deck}", self.a.level_games, f"{base}_{ro}_cp7", ro)
            rh, _, _ = battery(ck, deck, f"heuristic:{deck}", self.a.guard_games, f"{base}_{ro}_heur", ro)
            ck7, n7, s7 = rc.get(("cp7", deck), (0, 0, 0))
            kh, nh, _ = rh.get(("heuristic", deck), (0, 0, 0))
            lo, hi = wilson(ck7, n7) if n7 else (0.0, 0.0)
            g = int(n7 >= 100 and ck7 / n7 >= 0.70 and lo >= 0.60)
            lev[ro] = {"cp7": [ck7, n7], "heur": [kh, nh], "stalls": s7, "grad": g}
            if ro in ("sampled", "twostage"):       # argmax-classes is not a graduation readout (13c)
                grad = grad or g
        for key in ("cp7", "heur", "stalls"):
            lev[key] = lev["sampled"][key]
        lev["graduated"] = grad
        return lev, base

    def unseen(self, ck, deck, out):
        res, (k, n), _ = battery(ck, deck, UNSEEN, self.a.unseen_games, out)
        rows = ";".join(f"{d}={v[0]}/{v[1]}" for (kind, d), v in sorted(res.items()))
        return k, n, rows

    def level_line(self, m, lev, extra=""):
        L = self.st["mains"][m]
        k, n = lev["cp7"]
        kh, nh = lev["heur"]
        lo, hi = wilson(k, n) if n else (0, 0)
        loh, hih = wilson(kh, nh) if nh else (0, 0)
        two = lev.get("twostage", {}).get("cp7", ["", ""])
        arg = lev.get("argmax", {}).get("cp7", ["", ""])
        self.tsv("levels.tsv", [utc(), f"{self.hour():.3f}", m, lev["point"], lev["trained"], k, n,
                                f"{k / n:.3f}" if n else "", f"{lo:.3f}", f"{hi:.3f}", kh, nh,
                                f"{kh / nh:.3f}" if nh else "", f"{loh:.3f}", f"{hih:.3f}",
                                "", "", lev["graduated"], os.path.basename(lev["ck"]), two[0], two[1], arg[0], arg[1]])
        parts = ["L13", "level", m, f"point={lev['point']}", f"h={self.hour():.2f}", f"trained={lev['trained']}",
                 f"gained={lev['trained'] - L['start_ep']}"]
        for ro in READOUTS:
            r = lev.get(ro)
            if r:
                parts += [f"{ro}_cp7={fmt(*r['cp7'])}", f"{ro}_heur={fmt(*r['heur'])}", f"{ro}_stalls={r['stalls']}"]
        parts.append(f"graduated={lev['graduated']}" + extra)
        say(*parts)

    # ------------------------------------------------------------ tasks
    def t_start(self, m):
        L = self.st["mains"][m]
        ck = L["start_ck"]
        if self.a.start_level:
            lev, _ = self.level(m, ck, "start")
            L["levels"].append(lev)
            self.save()
            self.level_line(m, lev)
        say("L13", "start", m, f"ck={os.path.basename(ck)}", f"episodes={L['start_ep']}",
            f"start_level={'measured' if self.a.start_level else 'the 13b row'}",
            f"start_census={'recorded' if self.a.start_census else 'the 13b row'}")
        if self.a.start_census:
            self.census(m, ck, f"p13_{m}_start")

    def t_check(self, m, ck, ta, n):
        self.census(m, ck, f"p13_{m}_n{n:03d}_t{ta:05d}", n)

    def t_level(self, m, ck):
        L = self.st["mains"][m]
        lev, _ = self.level(m, ck, "train")
        L["levels"].append(lev)
        self.save()
        self.level_line(m, lev)
        if lev["graduated"] and not L["graduated"]:
            L["graduated"] = True
            g = f"{ART}/pool/{m}_grad.pt"
            shutil.copyfile(ck, g)
            self.save()
            say("L13", "grad", m, f"h={self.hour():.2f}", f"trained={lev['trained']}",
                f"gained={lev['trained'] - L['start_ep']}", f"sampled={fmt(*lev['sampled']['cp7'])}",
                f"twostage={fmt(*lev['twostage']['cp7'])}", f"frozen={g}")

    def t_end(self, m):
        L = self.st["mains"][m]
        if L["trained"] == L["start_ep"]:
            say("L13", "end", m, "no training - nothing to level")
            return
        if L["levels"] and L["levels"][-1]["trained"] == L["trained"]:
            say("L13", "end", m, f"last level already at {L['trained']}")
            return
        lev, _ = self.level(m, L["latest"], "end")
        L["levels"].append(lev)
        self.save()
        self.level_line(m, lev)

    def ensure_agent(self, m):
        L = self.st["mains"][m]
        agent = f"{L['out']}/agent.pt"
        os.makedirs(L["out"], exist_ok=True)
        if ck_episodes(agent) != L["trained"]:
            shutil.copyfile(L["latest"], agent)
            c = torch.load(agent, map_location="cpu", weights_only=False)
            if "opt" in c and c["opt"] is None:      # a BC checkpoint (opt=None) resumes like a stripped snapshot
                c.pop("opt")
                torch.save(c, agent + ".tmp")
                os.replace(agent + ".tmp", agent)
            say("L13", "restore", m, f"agent.pt <- {os.path.basename(L['latest'])}", f"episodes={L['trained']}")

    def block(self, m):
        a, L = self.a, self.st["mains"][m]
        pend = self.st.get("pending")
        if pend and pend["main"] == m:
            spec = pend
            say("L13", "rerun", m, f"budget={spec['budget']}", f"opp={spec['kind']}")
        else:
            self.ensure_agent(m)
            jl = f"{L['out']}/jobs.log"
            spec = {"main": m, "kind": ROTATION[L["blocks"] % len(ROTATION)], "tb": L["trained"],
                    "budget": L["trained"] + a.block, "jobs_off": os.path.getsize(jl) if os.path.exists(jl) else 0}
            self.st["pending"] = spec
            self.save()
        deck = L["deck"]
        env = dict(os.environ)
        env.update({"R0_ENCODER_V": "7", "R0_EVERY": str(a.block), "R0_CHUNK": "64", "R0_CP7_G": "0",
                    "R0_CONC": "4", "R0_LR": "3e-5", "RL_LOCK_STATS": "1", "RL_DRIVER_PORT": str(LANE_DPORT),
                    "R0_PORT": str(LANE_PORT), "R0_OPP_PORT": str(OPP_PORT), "R0_OUT": L["out"],
                    "R0_SRVEXTRA": SRVEXTRA, "R0_OPP_SPEC": f"{spec['kind']}::{deck}.dck",
                    "R0_ROWS": "none", "R0_ROWS_FINAL": "none", "R0_EVAL_G": "100",
                    "R0_INIT": L["start_ck"]})   # only copied to init.pt; agent.pt exists and is what resumes
        cmd = ["bash", f"{RL}/rung0_lane_league.sh", deck, deck, str(spec["budget"]), str(L["seed"])]
        free_lane()
        t0 = time.time()
        rc, ta = -1, 0
        for attempt in (1, 2):
            with open(f"{L['out']}/lane.log", "a") as fh:
                fh.write(f"# L12 block n={self.st['n']} attempt={attempt} {utc()} opp={spec['kind']}\n")
                fh.flush()
                rc = subprocess.call(cmd, env=env, stdout=fh, stderr=subprocess.STDOUT, cwd="/home/user/CardGuru")
            ta = ck_episodes(f"{L['out']}/agent.pt")
            if rc == 0 and ta >= spec["budget"] - 64:
                break
            say("L13", "error", m, f"attempt={attempt}", f"rc={rc}", f"trained={ta}", f"lane_log={L['out']}/lane.log")
        free_lane()
        wall = time.time() - t0
        ok = rc == 0 and ta >= spec["budget"] - 64
        W = Lo = D = S = E = N = 0
        jl = f"{L['out']}/jobs.log"
        if os.path.exists(jl):
            with open(jl) as fh:
                fh.seek(spec["jobs_off"])
                for line in fh:
                    E += line.startswith("RLJOB|error")
                    if line.startswith("RL|summary"):
                        kv = dict(t.split("=", 1) for t in line.strip().split("|")[2:] if "=" in t)
                        N += int(kv.get("episodes", 0)); W += int(kv.get("wins", 0)); Lo += int(kv.get("losses", 0))
                        D += int(kv.get("draws", 0)); S += int(kv.get("stalls", 0))
        snap = ""
        if ok:
            snap = f"{ART}/pool/{m}_{ta:05d}.pt"
            ck = torch.load(f"{L['out']}/agent.pt", map_location="cpu", weights_only=False)
            ck.pop("opt", None)
            torch.save(ck, snap + ".tmp")
            os.replace(snap + ".tmp", snap)
            for f in os.listdir(L["out"]):
                if f.startswith("ck_") and f.endswith(".pt"):
                    os.remove(os.path.join(L["out"], f))
        n = self.st["n"]
        self.tsv("results.tsv", [n, utc(), f"{self.hour():.3f}", m, spec["tb"], ta, spec["kind"], N, W, Lo, D, S,
                                 f"{W / N:.4f}" if N else "NA", E, os.path.basename(snap), f"{wall:.0f}", rc])
        say("L13", "block", f"n={n}", f"h={self.hour():.2f}", f"main={m}", f"trained={spec['tb']}->{ta}",
            f"opp={spec['kind']}", f"W/L/D/S={W}/{Lo}/{D}/{S}", f"wr={W / N:.3f}" if N else "wr=NA",
            f"errors={E}", f"wall={wall:.0f}s", f"rc={rc}")
        self.st["pending"] = None
        self.st["n"] += 1
        if not ok:
            self.st["fails"] += 1
            self.save()
            return
        self.st["fails"] = 0
        if L["tput"] is None or (spec["kind"] == "cp7" and not L.get("tput_cp7")) or \
                (spec["kind"] == "heuristic" and not L.get("tput_heur")):
            eph = (ta - spec["tb"]) / wall * 3600 if wall > 0 else 0
            L["tput"] = L["tput"] or round(eph, 1)
            L["tput_" + ("cp7" if spec["kind"] == "cp7" else "heur")] = round(eph, 1)
            say("L13", "tput", m, f"opp={spec['kind']}", f"episodes={ta - spec['tb']}", f"wall={wall:.0f}s",
                f"eps_per_h={eph:.0f}", f"h_per_1024={1024 / eph:.2f}" if eph else "h_per_1024=NA")
        L["blocks"] += 1
        L["trained"] = ta
        L["latest"] = snap
        self.st["todo"].append(["check", m, snap, ta, n])
        if (ta - L["start_ep"]) % a.level_every == 0:
            self.st["todo"].append(["level", m, snap])
        self.save()

    # ------------------------------------------------------------ loop
    def run(self):
        a = self.a
        reason = "?"
        while True:
            while self.st["todo"]:
                if os.path.exists(f"{ART}/STOP"):
                    break
                t = self.st["todo"][0]
                getattr(self, "t_" + t[0])(*t[1:])
                self.st["todo"].pop(0)
                self.save()
            if os.path.exists(f"{ART}/STOP"):
                reason = "stopfile"
                break
            if self.st.get("ended"):
                reason = self.st["ended"]
                break
            act = [m for m in a.mains.split(",") if m in ORDER]
            live = [m for m in ORDER if m in act and not self.st["mains"][m]["graduated"]]
            if not live:
                reason = "all_graduated"
            elif self.hour() >= a.hours:
                reason = "hours"
            elif self.st["fails"] >= 3:
                reason = "errors"
            else:
                pend = self.st.get("pending")
                m = pend["main"] if pend else None
                while m is None:
                    c = ORDER[self.st["rot"] % len(ORDER)]
                    self.st["rot"] += 1
                    m = c if c in live else None
                self.block(m)
                continue
            # end phase (not after a STOP): the last level + unseen suite for every main that did not graduate
            self.st["ended"] = reason
            self.st["todo"] += [["end", m] for m in act]
            self.save()
        free_lane()
        grads = ",".join(m for m in ORDER if self.st["mains"][m]["graduated"]) or "none"
        say("L13", "done", f"reason={reason}", f"blocks={self.st['n']}", f"h={self.hour():.2f}", f"graduated={grads}",
            *[f"{m}_trained={self.st['mains'][m]['trained'] - self.st['mains'][m]['start_ep']}" for m in ORDER])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hours", type=float, default=12.0, help="no new training block starts after this hour")
    ap.add_argument("--block", type=int, default=256)
    ap.add_argument("--level-every", type=int, default=1024)
    ap.add_argument("--level-games", type=int, default=100)
    ap.add_argument("--guard-games", type=int, default=50)
    ap.add_argument("--unseen-games", type=int, default=50)
    ap.add_argument("--census-games", type=int, default=25)
    ap.add_argument("--mains", default=",".join(ORDER),
                    help="mains that train and get the end phase (Amendment 2: M_D only); the others keep their state")
    ap.add_argument("--start-level", action="store_true", help="measure the start level (default: the 13b row)")
    ap.add_argument("--start-census", action="store_true", help="record the start census (default: the 13b row)")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    if a.dry_run:
        for m in ORDER:
            deck, ck, seed = MAINS[m]
            say("L13", "dry", m, deck, os.path.basename(ck), f"episodes={ck_episodes(ck)}", f"seed={seed}",
                "rotation=" + ",".join(ROTATION), "readouts=" + ",".join(READOUTS))
        say("L13", "dry", "srvextra=" + SRVEXTRA)
        return
    P12(a).run()


if __name__ == "__main__":
    main()
